steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "check-branch-name"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "master" ]; then
          _ENV='production'
        else
          _ENV=$BRANCH_NAME
        fi
        echo $${_ENV} > /workspace/env_var.txt

  - name: "gcr.io/cloud-builders/gcloud"
    id: "trigger-gateway-rebuild"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        _ENV=$(cat /workspace/env_var.txt)
        echo "Triggering gateway rebuild on branch=$_ENV..."
        gcloud builds triggers run gateway-trigger --branch="$_ENV"


substitutions:
  _LOCATION: "us-east1"
  _ENV: "main"

options:
  substitution_option: "ALLOW_LOOSE"
  logging: CLOUD_LOGGING_ONLY
